### ISSUE TITLE
Doesn't compile on Mac OS X 10.8.2

### ISSUE THREAD

**Issue by ghost** [SiegeLord/DAllegro5#5]
When trying to compile I get the following error message:
allegro5/file.d(25): Error: module freebsd is in file 'std/c/freebsd/freebsd.d' which cannot be read
import path[0] = /usr/local/Cellar/dmd/2.060/src/phobos
import path[1] = /usr/local/Cellar/dmd/2.060/src/druntime/import

Neither of these two modules paths exist on my system.

in both std/c/freebsd/ and std/c/osx/ there is only one file called socket.d

I'v got allegro 5.0.7 and dmd 2.060 (both from the Homebrew repositories) installed
